### PR TITLE
Updates the default value for the service id

### PR DESCRIPTION
**Pull request by Adamantios**
## Proposed changes

This updates the default value for the service id in order to trick the termination abci, which logs errors because the service is not deployed.

## Fixes

n/a

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [x] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

n/a

### CODE REVIEW

**Review by 0xArdi — APPROVED** [review]

**Comment by 8ball030** [comment]
thank you kind ser

**Review by 8ball030 — APPROVED** [review]

**Comment by 8ball030** [comment]
Yeah.,
That didnt do it.

image


What do i actually need to set this to please.

**Comment by Adamantios** [comment]
> Yeah., That didnt do it.
> 
> What do i actually need to set this to please.

@8ball030 Please let me know if it works now.

**Comment by Adamantios** [comment]
Closed because of inactivity.

Moreover, this was addressed properly on https://github.com/valory-xyz/open-autonomy/pull/1891 and will be available after bumping to `0.10.0`.

**Pull request closed without merging**
